"""Add reminder_sent_at to RentCharge

Revision ID: 33a7bd115403
Revises: 74137d9e2b61
Create Date: 2026-06-22 11:41:39.379517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33a7bd115403'
down_revision: Union[str, Sequence[str], None] = '74137d9e2b61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rent_charges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rent_charges', schema=None) as batch_op:
        batch_op.drop_column('reminder_sent_at')

    # ### end Alembic commands ###
