"""add payment deleted_at

Revision ID: 74137d9e2b61
Revises: c41d4caf4157
Create Date: 2026-06-22 10:47:20.468675

"""

from typing import Sequence, Union

# pyrefly: ignore [missing-import]
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "74137d9e2b61"
down_revision: Union[str, Sequence[str], None] = "c41d4caf4157"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
