"""Phase 1: rent charge and tenant changes

Revision ID: 934f135ba2f1
Revises: 4817bdeebb63
Create Date: 2026-06-22 10:06:31.434564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '934f135ba2f1'
down_revision: Union[str, Sequence[str], None] = '4817bdeebb63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rent_charges',
    sa.Column('agreement_id', sa.Uuid(), nullable=False),
    sa.Column('billing_month', sa.String(length=7), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('rent_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('late_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('upcoming', 'due', 'partial', 'paid', 'overdue', name='rentchargestatus'), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], name=op.f('fk_rent_charges_agreement_id_agreements'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_rent_charges_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rent_charges'))
    )
    with op.batch_alter_table('rent_charges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rent_charges_id'), ['id'], unique=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rent_charge_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_payments_rent_charge_id_rent_charges'), 'rent_charges', ['rent_charge_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_email'))
        batch_op.create_index(batch_op.f('ix_tenants_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_email'))
        batch_op.create_index(batch_op.f('ix_tenants_email'), ['email'], unique=1)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_payments_rent_charge_id_rent_charges'), type_='foreignkey')
        batch_op.drop_column('rent_charge_id')

    with op.batch_alter_table('rent_charges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rent_charges_id'))

    op.drop_table('rent_charges')
    # ### end Alembic commands ###
