"""multi_tenant

Revision ID: c41d4caf4157
Revises: 934f135ba2f1
Create Date: 2026-06-22 10:24:07.335254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c41d4caf4157'
down_revision: Union[str, Sequence[str], None] = '934f135ba2f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agreement_tenants',
    sa.Column('agreement_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], name=op.f('fk_agreement_tenants_agreement_id_agreements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_agreement_tenants_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agreement_id', 'tenant_id', name=op.f('pk_agreement_tenants'))
    )
    with op.batch_alter_table('agreements', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_agreements_tenant_id_tenants'), type_='foreignkey')
        batch_op.drop_column('tenant_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agreements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.CHAR(length=32), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_agreements_tenant_id_tenants'), 'tenants', ['tenant_id'], ['id'], ondelete='RESTRICT')

    op.drop_table('agreement_tenants')
    # ### end Alembic commands ###
